### ISSUE TITLE
Null pointer exception in JavaUI when save empty NDDL file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jariba/europa-pso#107]
```
If I edit my initial state file to remove everything, and then try saving in 
the IDE, it tells me the save failed due to a null pointer exception.  Here's 
the top of the stack trace:


java.lang.NullPointerException
    at org.ops.ui.editor.swt.NddlContentProvider.reload(NddlContentProvider.java:78)
    at org.ops.ui.editor.swt.NddlEditor.editorSaved(NddlEditor.java:88)
    at org.eclipse.ui.texteditor.AbstractTextEditor.performSave(AbstractTextEditor.java:4880)
    at org.eclipse.ui.texteditor.AbstractTextEditor.doSave(AbstractTextEditor.java:4668)
    at org.eclipse.ui.texteditor.AbstractTextEditor$TextEditorSavable.doSave(AbstractTextEditor.java:7003)
    at org.eclipse.ui.Saveable.doSave(Saveable.java:214)


Obviously this is a minor cleanup item, but also hopefully easy to fix.
```

Original issue reported on code.google.com by `tristanb...@gmail.com` on 4 Mar 2011 at 7:57

**Comment by GoogleCodeExporter** [comment]
```
Should work now
```

Original comment by `kichkaylo@gmail.com` on 17 Mar 2011 at 5:01
- Changed state: **Fixed**
