### ISSUE TITLE
ant build in PSUI expects a NDDLHellowWorld Driectory that is not present

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jariba/europa-pso#11]
```
What steps will reproduce the problem?
1.cd $EUROPA_HOME/src/PLASMA/System/component/PSUI
2.ant


What is the expected output? Something should run.

What do you see instead?

run:
     [echo] Running NDDLHelloWorld project
     [java]
/wg/adw/mcgann/ros/ros-pkg/wg-ros-pkg/stacks/trex/trex_core/PLASMA/src/PLASMA/Sy
stem/component/PSUI/build.xml:107:
/u/mcgann/workspace/NDDLHelloWorld is not a valid directory
     [java]     at org.apache.tools.ant.taskdefs.Java.fork(Java.java:732)
     [java]     at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:171)
     [java]     at org.apache.tools.ant.taskdefs.Java.execute(Java.java:84)
     [java]     at
org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:275)
     [java]     at org.apache.tools.ant.Task.perform(Task.java:364)
     [java]     at org.apache.tools.ant.Target.execute(Target.java:341)
     [java]     at org.apache.tools.ant.Target.performTasks(Target.java:369)
     [java]     at
org.apache.tools.ant.Project.executeSortedTargets(Project.java:1216)
     [java]     at org.apache.tools.ant.Project.executeTarget(Project.java:1185)
     [java]     at
org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:
40)
     [java]     at org.apache.tools.ant.Project.executeTargets(Project.java:1068)
     [java]     at org.apache.tools.ant.Main.runBuild(Main.java:668)
     [java]     at org.apache.tools.ant.Main.startAnt(Main.java:187)
     [java]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:246)
     [java]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:67)

```

Original issue reported on code.google.com by `mcgann.conor@gmail.com` on 9 Sep 2009 at 2:32

**Comment by GoogleCodeExporter** [comment]
Original comment by `mcgann.conor@gmail.com` on 16 Oct 2009 at 6:25

**Comment by GoogleCodeExporter** [comment]
```
I created the folder NDDLHelloWorld to get the script to advance.
Then it looks for a library called libSystem_o.so. Still trying to find that...
closest I found is $PLASMA_HOME/dist/europa/lib/libSystem_g.so
```

Original comment by `jasongho85@gmail.com` on 3 Feb 2010 at 1:25

Attachments:
- [tmp2.txt](https://storage.googleapis.com/google-code-attachments/europa-pso/issue-11/comment-2/tmp2.txt)

**Comment by GoogleCodeExporter** [comment]
Original comment by `javier.barreiro@gmail.com` on 22 Nov 2010 at 10:29
- Added labels: **Milestone-EUROPA-X**
