### ISSUE TITLE
Gantt chart view causes exception on start-up

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jariba/europa-pso#114]
```
Restart up the java UI with the gantt chart view visible.  It doesn't mess up 
functionality, but I see the following exception trace:

!ENTRY org.eclipse.ui 4 0 2011-03-14 13:56:04.685
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable 
(java.lang.NullPointerException)
    at org.eclipse.swt.SWT.error(SWT.java:4083)
    at org.eclipse.swt.SWT.error(SWT.java:3998)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:137)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3515)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3164)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2640)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2604)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2438)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:671)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:664)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:115)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:619)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:574)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1407)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1383)
Caused by: java.lang.NullPointerException
    at org.ops.ui.gantt.model.GanttModel.<init>(GanttModel.java:24)
    at org.ops.ui.gantt.model.GanttModel.<init>(GanttModel.java:20)
    at org.ops.ui.gantt.swt.GanttView.doUpdate(GanttView.java:246)
    at org.ops.ui.gantt.swt.GanttView.access$5(GanttView.java:245)
    at org.ops.ui.gantt.swt.GanttView$7.run(GanttView.java:294)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:134)
    ... 23 more
```

Original issue reported on code.google.com by `tristanb...@gmail.com` on 14 Mar 2011 at 8:58

**Comment by GoogleCodeExporter** [comment]
```
I am not getting any exceptions. Can you give more details on what's open, 
which perspective, etc?
```

Original comment by `kichkaylo@gmail.com` on 17 Mar 2011 at 5:09

**Comment by GoogleCodeExporter** [comment]
```
The problem is that the GanttModel constructor is called with solverModel=null, 
which causes the null pointer on the first line of the second GanttModel 
constructor.

I'll attach a screenshot of the views etc that are open when I startup.
```

Original comment by `tristanb...@gmail.com` on 17 Mar 2011 at 3:58

Attachments:
- [StartupPerspective.png](https://storage.googleapis.com/google-code-attachments/europa-pso/issue-114/comment-2/StartupPerspective.png)

**Comment by GoogleCodeExporter** [comment]
Original comment by `kichkaylo@gmail.com` on 18 Mar 2011 at 3:12
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I'm still seeing this.  I wonder if it got reintroduced by r6274.  It's the 
same line causing the assert in GanttModel constructor:

  this.resources = solverModel.getEngine().getObjectsByType(objectsTypes);

Now, however, solverModel is no longer null, BUT solverModel.getEngine() is 
null :).

```

Original comment by `tristanb...@gmail.com` on 18 Mar 2011 at 11:56
- Changed state: **Reopened**

**Comment by GoogleCodeExporter** [comment]
```
Try after r6278.
```

Original comment by `kichkaylo@gmail.com` on 24 Mar 2011 at 3:19

**Comment by GoogleCodeExporter** [comment]
```
Yep, seems to work now - thanks!
```

Original comment by `tristanb...@gmail.com` on 30 Mar 2011 at 7:24
- Changed state: **Verified**
