### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jariba/europa-pso#139]
```
What steps will reproduce the problem?
1.cd ~/europa/examples/Light
2.ant

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
ant -version : Apache Ant Version 1.7.1
Europa version: Europa-2.5-linux
OS: Ubuntu 10.04

Please provide any additional information below.
Buildfile: build.xml

init:

compile:
    [javac] Compiling 1 source file to /home/biyonder/europa/examples/Light/build/classes

run:
     [echo] Running Light project
     [java] Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/biyonder/europa/lib/libSystem_g.so: libResource_g.so: cannot open shared object file: No such file or directory
     [java]     at java.lang.ClassLoader$NativeLibrary.load(Native Method)
     [java]     at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1750)
     [java]     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1646)
     [java]     at java.lang.Runtime.load0(Runtime.java:787)
     [java]     at java.lang.System.load(System.java:1022)
     [java]     at psengine.util.LibraryLoader.loadLibrary(Unknown Source)
     [java]     at psengine.PSUtil.loadLibraries(Unknown Source)
     [java]     at Light.Main.main(Main.java:15)

BUILD FAILED
/home/biyonder/europa/examples/Light/build.xml:64: Java returned: 1

Total time: 2 seconds

```

Original issue reported on code.google.com by `biyonder...@gmail.com` on 2 Sep 2011 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
Please, i can't run any example. What is the mean of this error? What should I 
do? Thanks.
```

Original comment by `biyonder...@gmail.com` on 8 Sep 2011 at 7:17
