### ISSUE TITLE
libANML_g.so cannot open shared object file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jariba/europa-pso#149]
```
What steps will reproduce the problem?
1.
downloaded the distribution on 3/25/12 on Ubuntu 11.10
2.
installed europa under /home/jef/__APPS/europa/
3.
followed instruction under 
http://code.google.com/p/europa-pso/wiki/EuropaInstallation
4.
trying to run the Light example from Quickstart: 
http://code.google.com/p/europa-pso/wiki/QuickStart

What is the expected output? What do you see instead?

I see the following when running ant:

jef@MONTEVISTA:~/__PRJ/europa/Light$ ant
Buildfile: /home/jef/__PRJ/europa/Light/build.xml

init:

compile:

run:
     [echo] Running Light project
     [java] Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/jef/__APPS/europa/lib/libSystem_g.so: libANML_g.so: cannot open shared object file: No such file or directory
     [java]     at java.lang.ClassLoader$NativeLibrary.load(Native Method)
     [java]     at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1924)
     [java]     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
     [java]     at java.lang.Runtime.load0(Runtime.java:792)
     [java]     at java.lang.System.load(System.java:1059)
     [java]     at psengine.util.LibraryLoader.loadLibrary(Unknown Source)
     [java]     at psengine.PSUtil.loadLibraries(Unknown Source)
     [java]     at Light.Main.main(Main.java:17)

BUILD FAILED
/home/jef/__PRJ/europa/Light/build.xml:69: Java returned: 1


What version of the product are you using? On what operating system?
downloaded the distribution on 3/25/12 on Ubuntu 11.10


Please provide any additional information below.

```

Original issue reported on code.google.com by `jef.mang...@gmail.com` on 25 Mar 2012 at 7:04

**Comment by GoogleCodeExporter** [comment]
```
It also happened to me. I solved it by reading the installation manual:
http://code.google.com/p/europa-pso/wiki/EuropaInstallation

I added something like this to my .bashrc:

export EUROPA_HOME=~/europa
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$EUROPA_HOME/lib

Of course, in your case you'll need to change the first line into:
export EUROPA_HOME=~/__PRJ/europa/
```

Original comment by `felrob...@gmail.com` on 18 Apr 2012 at 8:30
